#!/usr/bin/env bash 
optspec=":-:"
while getopts "$optspec" optchar; do
    case "${optchar}" in
        -)
            case "${OPTARG}" in
                i1)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    i1="-i \"${val}\"";
                    ;;
                i2)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    i2="-i \"${val}\"";
                    ;;
                i3)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    i3="-i \"${val}\"";
                    ;;
                i4)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    i4="-i \"${val}\"";
                    ;;
                i5)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    i5="-i \"${val}\"";
                    ;;
                v)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    v="-map ${val}";
                    ;;
                a1)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    a1="-map ${val}";
                    ;;
                a2)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    a2="-map ${val} -disposition:a:1 0";
                    ;;
                a3)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    a3="-map ${val} -disposition:a:2 0";
                    ;;
                a4)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    a4="-map ${val} -disposition:a:3 0";
                    ;;
                s1)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    s1="-map ${val}";
                    ;;
                s2)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    s2="-map ${val} -disposition:s:1 0";
                    ;;
                s3)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    s3="-map ${val} -disposition:s:2 0";
                    ;;
                s4)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    s4="-map ${val} -disposition:s:3 0";
                    ;;
                s5)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    s5="-map ${val} -disposition:s:4 0";
                    ;;
                s6)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    s6="-map ${val} -disposition:s:5 0";
                    ;;
                s7)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    s7="-map ${val} -disposition:s:6 0";
                    ;;
                cv)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    cv="-c:v ${val}";
                    ;;
                cvc)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    cvc="-crf ${val}";
                    ;;
                ca1)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
					if [[ ${val} -eq "aac" ]]
					then
                        ca1="-c:a:0 libfdk_aac -vbr 4";
					elif [[ ${val} -eq "ac3" ]]
					then
					    ca1="-c:a:0 ac3 -b:a 640k"
					elif [[ ${val} -eq "mp3" ]]
					then
					    ca1="-c:a:0 libmp3lame -q 2" ]]
					else
                        ca1="-c:a:0 ${val}";
					fi
                    ;;
                ca1c)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    ca1c="-q ${val}";
                    ;;
                ca2)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
					if [[ ${val} -eq "aac" ]]
					then
                        ca2="-c:a:1 libfdk_aac -vbr 4";
					elif [[ ${val} -eq "ac3" ]]
					then
					    ca2="-c:a:1 ac3 -b:a 640k"
					elif [[ ${val} -eq "mp3" ]]
					then
					    ca2="-c:a:1 libmp3lame -q 2" ]]
					else
                        ca2="-c:a:1 ${val}";
					fi
                    ;;
                ca2c)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    ca2c="-q ${val}";
                    ;;
                ca3)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
					if [[ ${val} -eq "aac" ]]
					then
                        ca3="-c:a:2 libfdk_aac -vbr 4";
					elif [[ ${val} -eq "ac3" ]]
					then
					    ca3="-c:a:2 ac3 -b:a 640k"
					elif [[ ${val} -eq "mp3" ]]
					then
					    ca3="-c:a:2 libmp3lame -q 2" ]]
					else
                        ca3="-c:a:2 ${val}";
					fi
                    ;;
                ca3c)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    ca3c="-q ${val}";
                    ;;
                ca4)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
					if [[ ${val} -eq "aac" ]]
					then
                        ca3="-c:a:3 libfdk_aac -vbr 4";
					elif [[ ${val} -eq "ac3" ]]
					then
					    ca3="-c:a:3 ac3 -b:a 640k"
					elif [[ ${val} -eq "mp3" ]]
					then
					    ca3="-c:a:3 libmp3lame -q 2" ]]
					else
                        ca3="-c:a:3 ${val}";
					fi
                    ;;
                ca3c)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    ca4c="-q ${val}";
                    ;;
                lv1)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    lv1="-metadata:s:v:0 language=${val}";
                    ;;
                la1)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    la1="-metadata:s:a:0 language=${val}";
                    ;;
                la2)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    la2="-metadata:s:a:1 language=${val}";
                    ;;
                la3)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    la3="-metadata:s:a:2 language=${val}";
                    ;;
                ls1)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    ls1="-metadata:s:s:0 language=${val}";
                    ;;
                ls2)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    ls2="-metadata:s:s:1 language=${val}";
                    ;;
                ls3)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    ls3="-metadata:s:s:2 language=${val}";
                    ;;
                ls4)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    ls4="-metadata:s:s:3 language=${val}";
                    ;;
                ls5)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    ls5="-metadata:s:s:4 language=${val}";
                    ;;
                ls6)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    ls6="-metadata:s:s:5 language=${val}";
                    ;;
                ls7)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    ls7="-metadata:s:s:6 language=${val}";
                    ;;
                da1)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    da1="-disposition:a:0 ${val}";
                    ;;
                da2)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    da2="-disposition:a:1 ${val}";
                    ;;
                da3)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    da3="-disposition:a:2 ${val}";
                    ;;
                ds1)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    ds1="-disposition:s:0 ${val}";
                    ;;
                ds2)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    ds2="-disposition:s:1 ${val}";
                    ;;
                ds3)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    ds3="-disposition:s:2 ${val}";
                    ;;
                ta2)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    ta2="-metadata:s:a:1 title=${val}";
                    ;;
                ta3)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    ta3="-metadata:s:a:2 title=${val}";
                    ;;
                ts1)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    ts1="-metadata:s:s:0 title=\"${val}\"";
                    ;;
                ts2)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    ts2="-metadata:s:s:1 title=\"${val}\"";
                    ;;
                ts3)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    ts3="-metadata:s:s:2 title=\"${val}\"";
                    ;;
                ts4)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    ts4="-metadata:s:s:3 title=\"${val}\"";
                    ;;
                ts5)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    ts5="-metadata:s:s:4 title=\"${val}\"";
                    ;;
                ts6)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    ts6="-metadata:s:s:5 title=\"${val}\"";
                    ;;
                ts7)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    ts7="-metadata:s:s:6 title=\"${val}\"";
                    ;;
                ac)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    ac="-ac ${val}";
                    ;;
                af)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    af="-af aresample=async=1";
                    ;;
                target)
                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                    target="\"${val}\"";
                    ;;
            esac;;
    esac
done
if [ -z "$v" ]
then
    v="-map 0:v";
fi
if [ -z "$a1" ]
then
    a1="-map 0:a";
fi
if [ -z "$s1" ]
then
    s1="-map 0:s:0";
fi
echo ffmpeg $i1 $i2 $i3 $i4 $i5 $v $a1 $a2 $a3 $a4 $s1 $s2 $s3 $s4 $s5 $s6 $s7 -c copy $cv $cvc $ca1 $ca1c $ac $ca2 $ca2c $ca3 $ca3c $ca4 $ca4c $lv1 $la1 $la2 $la3 $ls1 $ls2 $ls3 $ls4 $ls5 $ls6 $ls7 $da1 $da2 $da3 $ds1 $ds2 $ds3 -metadata title= -metadata:s:v title= -metadata:s:a:0 title=  $ta2 $ta3 $ts1 $ts2 $ts3 $ts4 $ts5 $ts6 $ts7 -max_interleave_delta 0 $af -disposition:a:0 default -disposition:s:0 default $target
#read -p "Press enter to continue"
#ffmpeg $i1 $i2 $i3 $i4 $i5 $v $a1 $a2 $a3 $a4 $s1 $s2 $s3 $s4 -c copy $cv $cvc $ca1 $ca1c $ac $ca2 $ca2c $ca3 $ca3c $ca4 $ca4c $lv1 $la1 $la2 $la3 $ls1 $ls2 $ls3 $da1 $da2 $da3 $ds1 $ds2 $ds3 -metadata title= -metadata:s:v title= -metadata:s:a:0 title=  $ta2 $ta3 $ts1 $ts2 $ts3 $ts4 -max_interleave_delta 0 $af -disposition:a:0 default -disposition:s:0 default $target

